### ISSUE TITLE
Error When Spawning the application

### ISSUE THREAD

**Issue by chanpu9** [federicodotta/Brida#48]
Hi,

I found the error about node and frida-compile:
    env: node: No such file or directory  
    Error during frida-compile. Aborting.

How should I do fix the issue. I tried to do several ways found on Stackoverflow's site but I still found the error.
<img width="1194" alt="Screen Shot 2563-04-23 at 10 01 11" src="https://user-images.githubusercontent.com/43114750/80054524-ad034180-8549-11ea-8a24-972fe5661e48.png">

**Comment by federicodotta** [comment]
Hi chanpu9,

another user had your same issue and fixed by uninstalling and reinstalling the node environment.  I don't know on what OS are you working but maybe you can try to remove node and reinstall node from the official installer https://nodejs.org/en/download/

Federico

**Comment by chanpu9** [comment]
Federico,

My OS is macOS Catalina. I have uninstalled node and reinstalled from the official (https://nodejs.org/en/download/) but it is still the same:
          env: node: No such file or directory
          Error during frida-compile. Aborting.

**Comment by federicodotta** [comment]
Another user had your same issue on MacOS with node but he fixed reinstalling node. You can find the thread here:

https://github.com/federicodotta/Brida/issues/47#issuecomment-616920075

I wrote in this thread a message to him by asking how he solved.

**Comment by CTF-MissFeng** [comment]
Run from the command line：
frida-compile -x -o data/burp/brida/bridaGeneratedCompiledOutput.js data/burp/brida/brida.js

![image](https://user-images.githubusercontent.com/38177965/80279940-3a55ba00-8733-11ea-85fe-f5e4059df3ef.png)

ok！

**Comment by federicodotta** [comment]
Hi @chanpu9,

I did some researches and I discovered that MacOS has different $PATH environment variables for terminal application and for GUI applications. Probably you have the correct environment variable for frida-compile on the terminal but not for the GUI applications. (unfortunately I haven't a MacOS system)

Have a look on this:
https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x
And let me know if in this way you solve the issue.

Federico

**Comment by CTF-MissFeng** [comment]
> 嗨@ chanpu9，
> 
> 我做了一些研究，发现MacOS对于终端应用程序和GUI应用程序具有不同的$ PATH环境变量。可能您在终端上具有适用于frida-compile的正确环境变量，而对于GUI应用程序则没有。（不幸的是我没有MacOS系统）
> 
> 看看这个：
> [https](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x) : [//stackoverflow.com/questions/135688/setting-environment-variables-on-os-x](https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x)
> 并且让我知道您是否以此方式解决了这个问题。
> 
> 费德里科

This method does not work：

![image](https://user-images.githubusercontent.com/38177965/80309753-778c7b80-8809-11ea-8ea7-f3e1d6c9b9ee.png)

Windows：This problem also exists

![image](https://user-images.githubusercontent.com/38177965/80309796-c0443480-8809-11ea-8884-a5b2ca03d291.png)

The current solution is: manually perform the compilation

**Comment by CTF-MissFeng** [comment]
Modify the source code so that it does not execute：

![image](https://user-images.githubusercontent.com/38177965/80309960-bcfd7880-880a-11ea-8c3e-f8fd61074578.png)

Temporary method: manually compile the file：

![image](https://user-images.githubusercontent.com/38177965/80309980-d999b080-880a-11ea-9c5c-f00eeaf5d990.png)

Run successfully：

![image](https://user-images.githubusercontent.com/38177965/80310019-0cdc3f80-880b-11ea-9bd4-e81f60f7b2da.png)

**Comment by federicodotta** [comment]
Hi  @chanpu9 ,

From you screenshot you add to the PATH all the binary folders (/usr/local/bin, etc.), but node binary is in those folders? Because frida-compile fail to run node binary. Do you have "node" binary in the folders you added to PATH?

**Comment by CTF-MissFeng** [comment]
> Hi @cq-feng,
> 
> From you screenshot you add to the PATH all the binary folders (/usr/local/bin, etc.), but node binary is in those folders? Because frida-compile fail to run node binary. Do you have "node" binary in the folders you added to PATH?

Restarted the system：

![image](https://user-images.githubusercontent.com/38177965/80310561-fa173a00-880d-11ea-9c0c-6503b85e6549.png)

![image](https://user-images.githubusercontent.com/38177965/80310600-2e8af600-880e-11ea-9c21-8309e718d95c.png)

![image](https://user-images.githubusercontent.com/38177965/80310703-ae18c500-880e-11ea-852c-51ba2e5719e2.png)

**Comment by federicodotta** [comment]
Uhmm... It's very strange... I will ask to some friends with a MacOS to do a check in the next days and I will be back on you

A question: do you have whitespaces in the obfuscated part of the paths? Or some non-ASCII characters?

**Comment by CTF-MissFeng** [comment]
https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/

**Comment by federicodotta** [comment]
Great! Do you try this solution? Is it working?

**Comment by CTF-MissFeng** [comment]
Macos 10.15, Does not support APP to set global variables

**Comment by federicodotta** [comment]
Uhm, OK... I build a Brida binary in which I replaced frida-compile exec to "source ~/.profile; frida-compile". Can you try to add /usr/local/bin to your ~/.profile file and then try with this release?

[Brida-0.4-jar-with-dependencies.jar.zip](https://github.com/federicodotta/Brida/files/4535924/Brida-0.4-jar-with-dependencies.jar.zip)

Thank you!

**Comment by Neo01010** [comment]
![image](https://user-images.githubusercontent.com/15312660/80341840-b8ca6d00-8895-11ea-8db9-dff106eab1c2.png)
![image](https://user-images.githubusercontent.com/15312660/80341869-c5e75c00-8895-11ea-96d6-59ee2837ed3b.png)

**Comment by Neo01010** [comment]
The above method is still invalid，macos 10.15.4

**Comment by Neo01010** [comment]
https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/
It works！！！！

**Comment by federicodotta** [comment]
Great @Neo01010 !

@CTF-MissFeng, @Neo01010 just wrote that the method you posted [here](https://github.com/federicodotta/Brida/issues/48#issuecomment-619572006) works on MacOs 10.15. Is this method working for you too?

Thank you,
Federico

**Comment by mustafairan** [comment]
@federicodotta Just a confirmation; that solution worked for me. I haven't achieve to spawn the app but looks like that solved frida-compile problem. Thanks

**Comment by chanpu9** [comment]
@federicodotta Sorry for late reply. I have solved this issue via https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/. However, I found a new issue instead: java.io.IOException: Cannot run program "/usr/local/lib/node_modules/frida-compile": error=13, Permission denied, even if I have change the privilge folder: sudo chown -R $USER /usr/local/lib/node_modules/frida-compile.
<img width="1280" alt="Screen Shot 2563-06-08 at 21 36 45" src="https://user-images.githubusercontent.com/43114750/84043182-2eb30f80-a9d0-11ea-9f35-e7b7786bce06.png">

**Comment by Teeroy-tk** [comment]
make the folder /opt/burp/brida/ writeable...

**Comment by bypazs** [comment]
> https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/
> It works！！！！

could you share the command do you use in the terminal please.

I'm download

> Brida-0.4-jar-with-dependencies.jar.zip

 and  try `sudo launchctl config user path /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin`

Still not working 

> Exception during frida-compile java.io.IOException: Cannot run program "source": error=2, No such file or directory

**Comment by klmitchell2** [comment]
I've tried the above and no luck. This is where `frida-compile` is installed: 

`/Users/<user>/.nvm/versions/node/v12.5.0/bin/frida-compile`

Both result in `env: node: No such file or directory`

**Comment by hacker7744** [comment]
Hi,
I am facing an error: Please refer attached brida_console_log.txt file and attached screenshot.
how to resolve this issue?
[brida_console_log.txt](https://github.com/federicodotta/Brida/files/5432937/brida_console_log.txt)

![image](https://user-images.githubusercontent.com/30390369/97082740-8bcefb00-1629-11eb-8171-369e275481d9.png)

**Comment by ifishzz** [comment]
> 修改源代码，使其不执行：
> 
> ![图片](https://user-images.githubusercontent.com/38177965/80309960-bcfd7880-880a-11ea-8c3e-f8fd61074578.png)
> 
> 临时方法：手动编译文件：
> 
> ![图片](https://user-images.githubusercontent.com/38177965/80309980-d999b080-880a-11ea-9c5c-f00eeaf5d990.png)
> 
> 运行成功：
> 
> ![图片](https://user-images.githubusercontent.com/38177965/80310019-0cdc3f80-880b-11ea-9bd4-e81f60f7b2da.png)

Can you add to your WeChat account? Windows doesn’t know how to solve it

**Comment by YaphetsH** [comment]
This method(https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/ ) doesn't work on me(mac os 11.0.1 Big Sur)
can anyone help me?
![image](https://user-images.githubusercontent.com/11659777/103670357-6f015d00-4fb4-11eb-8996-b9410ef54721.png)

**Comment by YaphetsH** [comment]
> This method(https://dani.gg/467-add-usr-local-bin-to-the-path-variable-on-mac-os/ ) doesn't work on me(mac os 11.0.1 Big Sur)
> can anyone help me?
> ![image](https://user-images.githubusercontent.com/11659777/103670357-6f015d00-4fb4-11eb-8996-b9410ef54721.png)

I try to run burp with root or sudo grant ,that works~ Done

**Comment by federicodotta** [comment]
Hi,

I close the issue because a solution has been provided. I added the solution also in the Wiki at the following page:

- https://github.com/federicodotta/Brida/wiki/Troubleshooting

Please open a new issue if you still have problems.

Thank you,
Federico
